data:
  requestsCpu: "0.1"
  requestsMemory: "384M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  fileMinioSecretName: "file-minio-secret"
  fileKeycloakSecretName: "file-keycloak-secret"
  filePostgresSecretName: "file-postgres-secret"
  onPremEnabled: false
  domain: ""
