data:
  requestsCpu: "0.1"
  requestsMemory: "384M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  fileMinioSecretName: "minio-file-secret"
  fileKeycloakSecretName: "keycloak-file-secret"
  filePostgresSecretName: "postgres-file-secret"
  onPremEnabled: false
  domain: ""
