version: 2
updates:
  # ========================================================================
  # TEMPLATE REPOSITORY CONFIGURATION
  # ========================================================================
  # This configuration is for the TEMPLATE repository (azure/osdu-spi)
  # which serves as the engineering system/platform.
  #
  # ARCHITECTURE DECISION:
  # - Template owns: Engineering system (.github workflows and actions)
  # - Forks own: Application code (Maven dependencies)
  # - Updates flow: Template → sync-template → Forks
  #
  # Fork repositories receive .github updates via sync-template workflow,
  # NOT via their own dependabot. This eliminates race conditions and
  # duplicate PRs while maintaining clear separation of concerns.
  # ========================================================================

  # GitHub Actions - Engineering System (Template Responsibility)
  # Monitors ALL .github subdirectories recursively for workflow/action updates
  # Includes: workflows/, template-workflows/, actions/, local-actions/
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: "main"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5

  # Python/doc dependencies removed to prevent fork initialization issues
  # Issue: Forks inherit this config momentarily before deploy-fork-resources.sh runs,
  # causing Dependabot to cache the pip/doc ecosystem even after replacement
  # Template documentation updates can be monitored separately if needed
