variables:
  IBM_BUILD_SUBDIR: provider/file-ibm
  IBM_INT_TEST_SUBDIR: testing/file-test-ibm
  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-file-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-file-deploy

  #Azure
  AZURE_SERVICE: file
  AZURE_BUILD_SUBDIR: provider/file-azure
  AZURE_TEST_SUBDIR: testing/file-test-azure
  STAGING_CONTAINER_NAME: file-staging-area
  PERSISTENCE_CONTAINER_NAME: file-persistent-area
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD
  AZURE_SWAGGER_PATH: api/file/v2/swagger-ui/index.html

  #AWS
  AWS_BUILD_SUBDIR: provider/file-aws/build-aws
  AWS_TEST_SUBDIR: testing/file-test-aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: file
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-file

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"
    ref: m18-pipeline-update-mm

  - local: "devops/gc/pipeline/override-stages.yml"
