variables:
  IBM_BUILD_SUBDIR: provider/file-ibm
  #IBM_INT_TEST_SUBDIR: testing/file-test-ibm

  OSDU_GCP_BUILD_SUBDIR: provider/file-gcp-datastore
  # OSDU_GCP_INT_TEST_SUBDIR: testing/file-test-core
  OSDU_GCP_SERVICE: file
  OSDU_GCP_BUCKET: nice-etching-277309-file 
  OSDU_GCP_NAMESPACE: osdu-namespace
  OSDU_GCP_VPC_CONNECTOR: osdu-connector
  OSDU_GCP_RECORDS_ROOT_URL: https://os-storage-dot-nice-etching-277309.uc.r.appspot.com/api/storage/v2
  OSDU_GCP_VENDOR: gcp-datastore
  OSDU_GCP_USER_ID: common-user
  OSDU_GCP_APPLICATION_NAME: os-file
  OSDU_GCP_SERVICE_ACCOUNT: osdu-gcp-sa@nice-etching-277309.iam.gserviceaccount.com
  OSDU_GCP_ENV_VARS: OSDU_ENTITLEMENTS_URL=$OSDU_GCP_ENTITLEMENTS_URL,FILE_LOCATION_BUCKET_NAME=$OSDU_GCP_BUCKET,SPRING_CLOUD_GCP_DATASTORE_NAMESPACE=$OSDU_GCP_NAMESPACE,FILE_LOCATION_USER_ID=$OSDU_GCP_USER_ID,GCP_RECORDS_ROOT_URL=$OSDU_GCP_RECORDS_ROOT_URL --vpc-connector=$OSDU_GCP_VPC_CONNECTOR 
  OSDU_GCP_ENVIRONMENT: dev
  OSDU_GCP_PROJECT: nice-etching-277309
  OSDU_GCP_TENANT_NAME: osdu
  OSDU_GCP_DEPLOY_ENV: empty
  OSDU_GCP_PORT: 8080


include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'standard-setup.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'build/maven.yml'
    
  - project: "osdu/platform/ci-cd-pipelines"
    ref: 'master'
    file: "cloud-providers/ibm.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/gitlab-ultimate.yml'
  
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/fossa.yml'
  
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'publishing/pages.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    ref: 'osdu-gcp-cloudrun'
    file: 'cloud-providers/osdu-gcp-cloudrun.yml'
