global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  logLevel: "ERROR"

data:
  #Deployment
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  #Configmap
  logLevel: ""
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  storageHost: "http://storage"

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  fileMinioSecretName: "file-minio-secret"
  fileKeycloakSecretName: "file-keycloak-secret"
  filePostgresSecretName: "file-postgres-secret"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"
  sidecarInject: true
