data:
  #Deployment
  requestsCpu: "0.1"
  requestsMemory: "384M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  #Configmap
  logLevel: "ERROR"
  osduEntitlementsUrl: "http://entitlements/api/entitlements/v2/"
  partitionApi: "http://partition/api/partition/v1/"
  storageApi: "http://storage/api/storage/v2/"
  springProfilesActive: "gcp"
  obmMinioPartitionPropertiesPrefix: "file.minio"
  fileLocationUserId: ""

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  fileMinioSecretName: "file-minio-secret"
  fileKeycloakSecretName: "file-keycloak-secret"
  filePostgresSecretName: "file-postgres-secret"
  onPremEnabled: false
  domain: ""

istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
