global:
  domain: ""
  onPremEnabled: false

data:
  #Deployment
  requestsCpu: "10m"
  requestsMemory: "450Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  #Configmap
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  storageHost: "http://storage"
  springProfilesActive: "gcp"
  fileLocationUserId: ""

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  fileMinioSecretName: "file-minio-secret"
  fileKeycloakSecretName: "file-keycloak-secret"
  filePostgresSecretName: "file-postgres-secret"

istio:
  proxyCPU: "10m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
