apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  STORAGE_HOST: {{ .Values.data.storageHost | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  {{- if not .Values.global.onPremEnabled }}
  FILE_LOCATION_USER_ID: {{ .Values.data.fileLocationUserId  | quote }}
  {{- end }}
