package org.opengroup.osdu.file.util;

import com.google.common.base.Strings;

public class AuthUtil {
	public synchronized String getToken() throws Exception {
		String token = null;
		String vendor = System.getProperty("VENDOR", System.getenv("VENDOR"));
		if (Strings.isNullOrEmpty(token) && vendor.equals("gcp")) {
//			String serviceAccountFile = System.getProperty("INTEGRATION_TESTER", System.getenv("INTEGRATION_TESTER"));
//			String audience = System.getProperty("INTEGRATION_TEST_AUDIENCE",
//					System.getenv("INTEGRATION_TEST_AUDIENCE"));
      String serviceAccountFile = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAib3BlbmRlcyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjM5Yzg0ZGZhNDU3ZTRlMTZmODQ0OWYyZTRmMWY2ZTY3ZDE4NzM3YTkiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGdCdG1nQlBVYXl6eDNcblRxOGR0UmJQRlRHWUNZVzRKbDBTOG1rY0RuNjFXeHVZb2U4QWtaa0FpSVpSNXFaWjRwSTYvSVpmc3JQTThjOWhcblYxVGVTOGtVcVRXUjFqeTJMVlM3K0NvR3VOeEZGdkZhNmhPSXNJOFVwWE5TcU9QR0JUcWxwU1RqcnVyRCtrRGhcbk9tdlpTY0xYQTFMUVl2T0Fmb0Z6Y2xrWWt0YVNhVVBzcHZJUnJHbEZUdG9kS1JiZ3YyQ08zSGNqd3JNNFpCSUNcbnFWZ1UvTXRoYnBSTzJIeTdmcGFnY2h3TGJpRTN0K0JhVXFPQndneDlXRUJSVjNGYUxudVd1UU8zd3MrVjI2MlNcbjV2S1UvRlM1ank4SEpOREY0UnlET1RkOHhDb0RjZHNuTm9GM3JpRlhaZUNTZ3BEWXcxdHZXZm00ZFJ2cWtpVmZcbjBGTzg0ZnVQQWdNQkFBRUNnZ0VBRkVrNmdxMkFQbTFoNjlIUnRLaDF5TW04Qkc3MFQyRVY4NFhFODlmeUxGejBcbktrV2JuVnNSMWtVR21Mc0FuRW9TZ01ubUp4dEpBY2x4eEhoQ2hLQ3JORFpBVmhUbXlYNWdXbWNWOHliaE4xWmxcbkE1MEhxTXlJSUUvOUdlS1dRWk91cEZwSWRWK2MvYU1YSmU0QzN4bTVUWHdORHphdW94ZVJoRkU1OVNveXlPNFlcbjRZMk05K0hqYm5uTys3V2d5cyt6blRvd1FoeWZNOXVJRklTV0ZWVnpwRGhFenhFOWFPY0EwL3ZjdFlnbFR0bWJcbkdUbHBrcmEvb0tXVGsrVTBsbi9GRGticngvYmovaVlMSlhVb3BaN3pZVUpvYU8yK21wVHk1ZmU5aVhSWjR5aDRcblhGOVpndXRlTmttVk12eENEZFU0NXcxQVpHNVZPRXozTzdYbDkySWdIUUtCZ1FENkRGRU5TSndINjRFVUFIcStcbnFSaFQ3Ny9mNnlUV0RJcitESlA3R2VFRGpwK2E5STQ3dDRTVVlxZFh0R2NyOFJBNjdKMHFJOGczOGtyeDYvd2VcbnlwWGpWN1hYdVBWeDJuOWU5QVArRGdmdkFBV0dGSnZHMi9pZnNSOHZGM0RtbjR5N21KbGtOY3NLSHVTWWZnMmNcbnRoNWlHVXhNRURRMVNRNERCMVI5WGxjVlBRS0JnUURsVy9pRmYxT1RPVVNJamMzMjRVcVdURmJUdXZEQ3haK1VcbkNOelpQZjNvcWxQbXVXMktuNm4wLzZwdFVIK0RWQWYvQ0Z0TnYrSmtUYjZpbWdsOXdSL0pHUEhJNzA3MEN3aThcbnBKeFZuaWlTZmhUc0hxTUhHSDZWN2kyamZSUExDVFJTdEJkWmdrdnoxMWl3am1NWHptS0NweCsyVjNKMW9GSmxcbkl2ZEVtR0xZdXdLQmdRQ0tWWUFOeWtyUU11RUJVTmFYWG5OZ0ZIWmhpZlNpR3VSV2NsejRBVFEwUkpaV0l0QUJcbmg2RG9lcis3ek1sN1RPMCt2Q0tpNnBMZEtNVi9tNStxNVVjUk5EZ2M5VzJNcEdYdEFUQ29QOWp4eDJCRzhtWFFcbkdXZ3Q2TTZvdmQ0dktMdXlHVlZiVkV0VStReGN0UGdRNTh4ZFYwT1huU3RWQTJxbUVFc1U1TGxtdlFLQmdBUm1cbkxERWJUUllRemlDMFg1UHhwRVdYdHo2ZVlrbktFcEo3VFFrWnFFb1RJa0xWb2FVOEJMMS9QZHlVNDYwNEttTVlcbjNPOXowN3JLeHZKRmRCTW1aaDZzVE03bTBDUGNKbEcvOG9PdDRlZFZaYjlWb3hqYXZtclB3NjVVRXRJZEhoVE1cbkFYcWxCaUhxS25oUWN0UWRFRVNqUWZkMFcreW5vNHp2QzhFVUR5bExBb0dBYlk3TmxKMmYzZm1MTnc3OGQ2V09cbmt0ejk4dHJGOEJOazRnelpZZEQ3MEpCQk01RXpWNyt6NXZ4TXVtNE5xejZlc0tEOGZvSkk5dlJabGNBS1pWSWpcbmJCdDN3c1VCVlFXN1pzK1d5cFJaSzQ3ZjlVaHF0RlRjL3lrd3doQm1vUk9uWllhYkJxcSsrRUVFeCtlbmZyS3RcbklTdW1hWmt3SEw0ck5pQUlTd3BUSjljPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImludGVncmF0aW9udGVzdEBvcGVuZGVzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExNjk2MjY1Nzg0MDU3OTg3OTIzNCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvaW50ZWdyYXRpb250ZXN0JTQwb3BlbmRlcy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo";
      String audience = "245464679631-ktfdfpl147m1mjpbutl00b3cmffissgq.apps.googleusercontent.com";
			token = new GoogleServiceAccount(serviceAccountFile).getAuthToken(audience);
		} else if ("aws".equals(vendor)) {
			System.out.println("Token generation code for aws comes here");
		} else if ("azure".equals(vendor)) {
			System.out.println("Token generation code for azure comes here");
		} else if ("ibm".equals(vendor)) {
			System.out.println("Token generation code for ibm comes here");
		}
		System.out.println("Bearer " + token);
		return "Bearer " + token;
	}
}
