variables:
  GC_SERVICE: file
  GC_VENDOR: gc-datastore

gc-dev2-test:
  variables:
    GC_VENDOR: gc
    DOMAIN: $GROUP_ID

gc-test:
  variables:
    VENDOR: gcp
    GC_VENDOR: gc
    HOST: https://community.gcp.gnrg-osdu.projects.epam.com/api/file/v2
    CLOUD_DOMAIN: $GROUP_ID
    INTEGRATION_TESTER: $GC_INTEGRATION_TESTER_SA_FILE
    NO_DATA_ACCESS_TESTER: $GC_NO_DATA_ACCESS_TESTER_FILE
    SEARCH_INTEGRATION_TESTER: $GC_INTEGRATION_TESTER_SA_FILE
    DE_OPS_TESTER: $GC_R3_OPS_TESTER_FILE
    DE_ADMIN_TESTER: $GC_R3_ADMIN_TESTER_FILE
    DE_EDITOR_TESTER: $GC_R3_EDITOR_TESTER_FILE
    DE_NO_ACCESS_TESTER: $GC_R3_NO_ACCESS_TESTER_FILE
    LEGAL_TAGS: $LEGAL_TAG
    DOMAIN: $GROUP_ID
  script:
    - echo "COMMON TESTS"
    - >
      $MAVEN_BUILD . test-results.log
      verify -DdisableXmlReport=true
      --quiet
      --file $GC_TESTING_DIR/pom.xml
      --projects $GC_TEST_PROJECT
      --update-snapshots
    - echo "ADDITIONAL TESTS"
    - >
      $MAVEN_BUILD . test-results.log
      verify -DdisableXmlReport=true
      --quiet
      --file $GC_TESTING_DIR/file-test-core-bdd/pom.xml
      --update-snapshots
  artifacts:
    when: always
    paths:
      - test-results.log
    expire_in: 2 days
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$GC == "1" && $GC_INT_TEST_TYPE != "python"'
      when: on_success
