name: Release Management

on:
  push:
    branches: [main]

permissions:
  contents: read

# Only run in the template repository
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == 'azure/osdu-spi'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42  # v2.1.4
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Generate Release PR
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38  # v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
